version: '3.8'

services:
  db:
    container_name: postgres-webtronics
    image: postgres:14
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  api:
    container_name: api-webtronics
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0
    restart: on-failure
    depends_on:
      - db
